[build]
  command = "npm run build"
  publish = "dist/browser"

[[edge_functions]]
  path = "/*"
  function = "angular-ssr"
  exclude_pattern = "\\.(js|css|ico|jpg|png|svg)$|^/assets/"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 4200
  targetPort = 4200

# Make static assets bypass the Edge Function completely
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = true

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true

# This should be the last redirect - catch all remaining routes for SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-ssr"
  status = 200
